### ISSUE TITLE
请教一个问题，这个sql文件要怎么初始化呀。好像没有sql文件欸

### ISSUE THREAD

**Issue by CocaineCong** [congz666/cmall-go#3]

**Comment by congz666** [comment]
使用的gorm连接的数据库 具体的代码可以看 [model/init.go](https://github.com/congz666/cmall-go/blob/master/model/init.go)

**Comment by weilongyun** [comment]
关键是没有sql表呀，看代码也没意义呢，没有整个商城的表结构么

**Comment by congz666** [comment]
只需创建数据库即可，表由gorm根据结构体定义自动生成，具体参阅model/migration和gorm官方文档



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月4日(星期一) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [congz666/cmall-go] 请教一个问题，这个sql文件要怎么初始化呀。好像没有sql文件欸 (#3)





 
关键是没有sql表呀，看代码也没意义呢，没有整个商城的表结构么
