### ISSUE TITLE
sql文件

### ISSUE THREAD

**Issue by seamusopen** [congz666/cmall-go#6]
sql文件是否可以提供下呢，项目不会自动创建sql表结构

**Comment by congz666** [comment]
项目是可以自动创建sql表的，不过你要先创建一个database然后写在env配置语句里

**Comment by seamusopen** [comment]
可以加您一个联系方式吗

**Comment by seamusopen** [comment]
@congz666 可以加您一个联系方式吗

**Comment by congz666** [comment]
> @congz666 可以加您一个联系方式吗

加我vx吧 a291905714
